///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MakeMyTrip.HomePage
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FromAndToCity recording.
    /// </summary>
    [TestModule("e60677e2-ac0b-4f7b-b827-83c44354acf3", ModuleType.Recording, 1)]
    public partial class FromAndToCity : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::MakeMyTrip.MakeMyTripRepository repository.
        /// </summary>
        public static global::MakeMyTrip.MakeMyTripRepository repo = global::MakeMyTrip.MakeMyTripRepository.Instance;

        static FromAndToCity instance = new FromAndToCity();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FromAndToCity()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FromAndToCity Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MakeMyTrip.OneWayJourney.Btn_From' at 13;7.", repo.MakeMyTrip.OneWayJourney.Btn_FromInfo, new RecordItemIndex(0));
            repo.MakeMyTrip.OneWayJourney.Btn_From.Click("13;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MakeMyTrip.OneWayJourney.TxtField_Search' at 40;23.", repo.MakeMyTrip.OneWayJourney.TxtField_SearchInfo, new RecordItemIndex(1));
            repo.MakeMyTrip.OneWayJourney.TxtField_Search.Click("40;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Hyderabad' with focus on 'MakeMyTrip.OneWayJourney.TxtField_Search'.", repo.MakeMyTrip.OneWayJourney.TxtField_SearchInfo, new RecordItemIndex(2));
            repo.MakeMyTrip.OneWayJourney.TxtField_Search.PressKeys("Hyderabad");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Hyderabad') on item 'MakeMyTrip.OneWayJourney.Hyderabad'.", repo.MakeMyTrip.OneWayJourney.HyderabadInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.MakeMyTrip.OneWayJourney.HyderabadInfo, "InnerText", "Hyderabad");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MakeMyTrip.OneWayJourney.Hyderabad' at 23;0.", repo.MakeMyTrip.OneWayJourney.HyderabadInfo, new RecordItemIndex(4));
            repo.MakeMyTrip.OneWayJourney.Hyderabad.Click("23;0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MakeMyTrip.OneWayJourney.Btn_To' at 6;11.", repo.MakeMyTrip.OneWayJourney.Btn_ToInfo, new RecordItemIndex(5));
            repo.MakeMyTrip.OneWayJourney.Btn_To.Click("6;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MakeMyTrip.OneWayJourney.TxtField_Search' at 40;24.", repo.MakeMyTrip.OneWayJourney.TxtField_SearchInfo, new RecordItemIndex(6));
            repo.MakeMyTrip.OneWayJourney.TxtField_Search.Click("40;24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Pune' with focus on 'MakeMyTrip.OneWayJourney.TxtField_Search'.", repo.MakeMyTrip.OneWayJourney.TxtField_SearchInfo, new RecordItemIndex(7));
            repo.MakeMyTrip.OneWayJourney.TxtField_Search.PressKeys("Pune");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Pune') on item 'MakeMyTrip.OneWayJourney.Pune'.", repo.MakeMyTrip.OneWayJourney.PuneInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.MakeMyTrip.OneWayJourney.PuneInfo, "InnerText", "Pune");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MakeMyTrip.OneWayJourney.Pune' at Center.", repo.MakeMyTrip.OneWayJourney.PuneInfo, new RecordItemIndex(9));
            repo.MakeMyTrip.OneWayJourney.Pune.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
