///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MakeMyTrip.FlightsList
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The clickOk recording.
    /// </summary>
    [TestModule("3ce535a4-0f8f-4c69-881e-206c28c9bd78", ModuleType.Recording, 1)]
    public partial class clickOk : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::MakeMyTrip.MakeMyTripRepository repository.
        /// </summary>
        public static global::MakeMyTrip.MakeMyTripRepository repo = global::MakeMyTrip.MakeMyTripRepository.Instance;

        static clickOk instance = new clickOk();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public clickOk()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static clickOk Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MakeMyTrip.BookingPage.Btn_OkayGotIt' at 41;13.", repo.MakeMyTrip.BookingPage.Btn_OkayGotItInfo, new RecordItemIndex(0));
            repo.MakeMyTrip.BookingPage.Btn_OkayGotIt.Click("41;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MakeMyTrip.BookingPage.RdBtn_NoTripSecure' at 12;8.", repo.MakeMyTrip.BookingPage.RdBtn_NoTripSecureInfo, new RecordItemIndex(1));
            repo.MakeMyTrip.BookingPage.RdBtn_NoTripSecure.Click("12;8");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
