///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MakeMyTrip.FlightsList
{
    public partial class Select_Indigo_Verify_Filtered_Flights
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void selectChkBoxAndGetTxt(RepoItemInfo ptagInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ptagInfo' at 6;8.", ptagInfo);
            ptagInfo.FindAdapter<PTag>().Click();
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ptagInfo' and assigning its value to variable 'flightName'.", ptagInfo);
            flightName = ptagInfo.FindAdapter<PTag>().Element.GetAttributeValueText("InnerText").Trim();
            MakeMyTripRepository mmt = new MakeMyTripRepository();
            var items = mmt.MakeMyTrip.Self.Find(".//p[@class='boldFont blackText airlineName']");
            foreach (var item in items){
            	string uiFlight = item.GetAttributeValueText("InnerText").Trim();
            	Report.Info("UI Flight Name: " + uiFlight);
            	Report.Info("Filter Flight Name: " + flightName);
            	if(uiFlight.Contains(flightName))
            	{
            		Report.Success("Flight matches filter: " + uiFlight);
            	}
            	else
            	{
            		Report.Failure("Flight does NOT match filter! Found: " + uiFlight);
            	}
            }
            
//            string Name = flightName.Trim();
//            Report.Info(Name);
//            
//            
//            MakeMyTripRepository mmt = new MakeMyTripRepository();
//            string filteredFlights = mmt.MakeMyTrip.fliteredFlight.Element.GetAttributeValueText("InnerText");
//            
//            Report.Info(filteredFlights);
  
            
            
            
            
            
            
            
            
        }
        
        

    }
}
