///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MakeMyTrip.FlightsList
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Select_Indigo_Verify_Filtered_Flights recording.
    /// </summary>
    [TestModule("6c608de2-7f6c-4654-9224-a0185b3605ff", ModuleType.Recording, 1)]
    public partial class Select_Indigo_Verify_Filtered_Flights : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::MakeMyTrip.MakeMyTripRepository repository.
        /// </summary>
        public static global::MakeMyTrip.MakeMyTripRepository repo = global::MakeMyTrip.MakeMyTripRepository.Instance;

        static Select_Indigo_Verify_Filtered_Flights instance = new Select_Indigo_Verify_Filtered_Flights();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Select_Indigo_Verify_Filtered_Flights()
        {
            flightName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Select_Indigo_Verify_Filtered_Flights Instance
        {
            get { return instance; }
        }

#region Variables

        string _flightName;

        /// <summary>
        /// Gets or sets the value of variable flightName.
        /// </summary>
        [TestVariable("ab24b604-4524-441a-8299-0c652d28aabf")]
        public string flightName
        {
            get { return _flightName; }
            set { _flightName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            selectChkBoxAndGetTxt(repo.MakeMyTrip.FlightListPage.ChxBox_FlightInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
