///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MakeMyTrip.FlightsList
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The verifyFilteredFlights recording.
    /// </summary>
    [TestModule("cd178ab4-77e1-45cb-8da9-885cef1050ca", ModuleType.Recording, 1)]
    public partial class verifyFilteredFlights : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::MakeMyTrip.MakeMyTripRepository repository.
        /// </summary>
        public static global::MakeMyTrip.MakeMyTripRepository repo = global::MakeMyTrip.MakeMyTripRepository.Instance;

        static verifyFilteredFlights instance = new verifyFilteredFlights();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public verifyFilteredFlights()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static verifyFilteredFlights Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Class='boldFont blackText airlineName') on item 'MakeMyTrip.HomePage.Txt_fliteredFlights'.", repo.MakeMyTrip.HomePage.Txt_fliteredFlightsInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.MakeMyTrip.HomePage.Txt_fliteredFlightsInfo, "Class", "boldFont blackText airlineName");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (data-test='component-airlineHeading') on item 'MakeMyTrip.HomePage.Txt_fliteredFlights'.", repo.MakeMyTrip.HomePage.Txt_fliteredFlightsInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.MakeMyTrip.HomePage.Txt_fliteredFlightsInfo, "data-test", "component-airlineHeading");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MakeMyTrip.HomePage.Txt_fliteredFlights' at 19;9.", repo.MakeMyTrip.HomePage.Txt_fliteredFlightsInfo, new RecordItemIndex(2));
            repo.MakeMyTrip.HomePage.Txt_fliteredFlights.Click("19;9");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
