///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MakeMyTrip.BookingPage
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Apply_Coupon_And_Validate_Price recording.
    /// </summary>
    [TestModule("471c057b-4254-489b-a479-8155def55ca8", ModuleType.Recording, 1)]
    public partial class Apply_Coupon_And_Validate_Price : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::MakeMyTrip.MakeMyTripRepository repository.
        /// </summary>
        public static global::MakeMyTrip.MakeMyTripRepository repo = global::MakeMyTrip.MakeMyTripRepository.Instance;

        static Apply_Coupon_And_Validate_Price instance = new Apply_Coupon_And_Validate_Price();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Apply_Coupon_And_Validate_Price()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Apply_Coupon_And_Validate_Price Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MakeMyTrip.FlightList.SpanTag11411' at 36;12.", repo.MakeMyTrip.FlightList.SpanTag11411Info, new RecordItemIndex(0));
            repo.MakeMyTrip.FlightList.SpanTag11411.Click("36;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MakeMyTrip.FlightList.Apply' at 19;14.", repo.MakeMyTrip.FlightList.ApplyInfo, new RecordItemIndex(1));
            repo.MakeMyTrip.FlightList.Apply.Click("19;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(2));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 240 units.", new RecordItemIndex(3));
            Mouse.ScrollWheel(240);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MakeMyTrip.FlightList.CouponV2OverlayWrapper' at 320;300.", repo.MakeMyTrip.FlightList.CouponV2OverlayWrapperInfo, new RecordItemIndex(4));
            repo.MakeMyTrip.FlightList.CouponV2OverlayWrapper.Click("320;300");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
