///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MakeMyTrip.BookingPage
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EnterTravellerDetails recording.
    /// </summary>
    [TestModule("ff9b8d11-54a3-4b79-8f35-47e1d19c56e4", ModuleType.Recording, 1)]
    public partial class EnterTravellerDetails : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::MakeMyTrip.MakeMyTripRepository repository.
        /// </summary>
        public static global::MakeMyTrip.MakeMyTripRepository repo = global::MakeMyTrip.MakeMyTripRepository.Instance;

        static EnterTravellerDetails instance = new EnterTravellerDetails();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EnterTravellerDetails()
        {
            FirstName = "Jagadeesh";
            LastName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EnterTravellerDetails Instance
        {
            get { return instance; }
        }

#region Variables

        string _FirstName;

        /// <summary>
        /// Gets or sets the value of variable FirstName.
        /// </summary>
        [TestVariable("e79a8bf7-094d-474d-b13c-31b7d39a1375")]
        public string FirstName
        {
            get { return _FirstName; }
            set { _FirstName = value; }
        }

        string _LastName;

        /// <summary>
        /// Gets or sets the value of variable LastName.
        /// </summary>
        [TestVariable("57dcb3f0-5484-4cd5-bbae-0ef535fd5521")]
        public string LastName
        {
            get { return _LastName; }
            set { _LastName = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Gender.
        /// </summary>
        [TestVariable("d162fbba-89be-4ffc-b1c0-23e8a69110cd")]
        public string Gender
        {
            get { return repo.Gender; }
            set { repo.Gender = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MakeMyTrip.TravellerDetails.Btn_AddNewAdult' at Center.", repo.MakeMyTrip.TravellerDetails.Btn_AddNewAdultInfo, new RecordItemIndex(0));
            repo.MakeMyTrip.TravellerDetails.Btn_AddNewAdult.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MakeMyTrip.TravellerDetails.TxtField_FirstName' at Center.", repo.MakeMyTrip.TravellerDetails.TxtField_FirstNameInfo, new RecordItemIndex(1));
            repo.MakeMyTrip.TravellerDetails.TxtField_FirstName.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$FirstName' with focus on 'MakeMyTrip.TravellerDetails.TxtField_FirstName'.", repo.MakeMyTrip.TravellerDetails.TxtField_FirstNameInfo, new RecordItemIndex(2));
            repo.MakeMyTrip.TravellerDetails.TxtField_FirstName.PressKeys(FirstName);
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MakeMyTrip.TravellerDetails.TxtField_LastName' at Center.", repo.MakeMyTrip.TravellerDetails.TxtField_LastNameInfo, new RecordItemIndex(3));
            repo.MakeMyTrip.TravellerDetails.TxtField_LastName.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$LastName' with focus on 'MakeMyTrip.TravellerDetails.TxtField_LastName'.", repo.MakeMyTrip.TravellerDetails.TxtField_LastNameInfo, new RecordItemIndex(4));
            repo.MakeMyTrip.TravellerDetails.TxtField_LastName.PressKeys(LastName);
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MakeMyTrip.BookingPage.Btn_Gender' at Center.", repo.MakeMyTrip.BookingPage.Btn_GenderInfo, new RecordItemIndex(5));
            repo.MakeMyTrip.BookingPage.Btn_Gender.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MakeMyTrip.BookingPage.Chkbox_Adult' at Center.", repo.MakeMyTrip.BookingPage.Chkbox_AdultInfo, new RecordItemIndex(6));
            repo.MakeMyTrip.BookingPage.Chkbox_Adult.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
