///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MakeMyTrip.BookingPage
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EnterTravellerDetails recording.
    /// </summary>
    [TestModule("ff9b8d11-54a3-4b79-8f35-47e1d19c56e4", ModuleType.Recording, 1)]
    public partial class EnterTravellerDetails : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::MakeMyTrip.MakeMyTripRepository repository.
        /// </summary>
        public static global::MakeMyTrip.MakeMyTripRepository repo = global::MakeMyTrip.MakeMyTripRepository.Instance;

        static EnterTravellerDetails instance = new EnterTravellerDetails();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EnterTravellerDetails()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EnterTravellerDetails Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MakeMyTrip.ButtonTagPlusADDNEWADULT' at 46;9.", repo.MakeMyTrip.ButtonTagPlusADDNEWADULTInfo, new RecordItemIndex(0));
            repo.MakeMyTrip.ButtonTagPlusADDNEWADULT.Click("46;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MakeMyTrip.BookingPage.TxtField_FirstName' at 97;25.", repo.MakeMyTrip.BookingPage.TxtField_FirstNameInfo, new RecordItemIndex(1));
            repo.MakeMyTrip.BookingPage.TxtField_FirstName.Click("97;25");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MakeMyTrip.Text' at 107;22.", repo.MakeMyTrip.TextInfo, new RecordItemIndex(2));
            repo.MakeMyTrip.Text.Click("107;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MakeMyTrip.BookingPage.Btn_Gender' at 106;28.", repo.MakeMyTrip.BookingPage.Btn_GenderInfo, new RecordItemIndex(3));
            repo.MakeMyTrip.BookingPage.Btn_Gender.Click("106;28");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MakeMyTrip.BookingPage.Chkbox_Adult1' at 1;12.", repo.MakeMyTrip.BookingPage.Chkbox_Adult1Info, new RecordItemIndex(4));
            repo.MakeMyTrip.BookingPage.Chkbox_Adult1.Click("1;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MakeMyTrip.ButtonTagPlusADDNEWADULT' at 68;5.", repo.MakeMyTrip.ButtonTagPlusADDNEWADULTInfo, new RecordItemIndex(5));
            repo.MakeMyTrip.ButtonTagPlusADDNEWADULT.Click("68;5");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
