///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MakeMyTrip.BookingPage
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Test recording.
    /// </summary>
    [TestModule("851e0f35-3281-48ce-9d94-7bccb13e9cc9", ModuleType.Recording, 1)]
    public partial class Test : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::MakeMyTrip.MakeMyTripRepository repository.
        /// </summary>
        public static global::MakeMyTrip.MakeMyTripRepository repo = global::MakeMyTrip.MakeMyTripRepository.Instance;

        static Test instance = new Test();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Test()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Test Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MakeMyTrip.FlightListPage.Txt_FirstName' at 17;4.", repo.MakeMyTrip.FlightListPage.Txt_FirstNameInfo, new RecordItemIndex(0));
            repo.MakeMyTrip.FlightListPage.Txt_FirstName.Click(new Location(Txt_FirstName_Screenshot1, "17;4", Txt_FirstName_Screenshot1_Options));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Jagadeesh' with focus on 'MakeMyTrip.FlightListPage.Txt_FirstName'.", repo.MakeMyTrip.FlightListPage.Txt_FirstNameInfo, new RecordItemIndex(1));
            repo.MakeMyTrip.FlightListPage.Txt_FirstName.PressKeys("Jagadeesh");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MakeMyTrip.TravellerDetails.TxtField_LastName' at 5;5.", repo.MakeMyTrip.TravellerDetails.TxtField_LastNameInfo, new RecordItemIndex(2));
            repo.MakeMyTrip.TravellerDetails.TxtField_LastName.Click(new Location(TxtField_LastName_Screenshot1, "5;5", TxtField_LastName_Screenshot1_Options));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Palavalsa' with focus on 'MakeMyTrip.TravellerDetails.TxtField_LastName'.", repo.MakeMyTrip.TravellerDetails.TxtField_LastNameInfo, new RecordItemIndex(3));
            repo.MakeMyTrip.TravellerDetails.TxtField_LastName.PressKeys("Palavalsa");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage Txt_FirstName_Screenshot1
        { get { return repo.MakeMyTrip.FlightListPage.Txt_FirstNameInfo.GetScreenshot1(new Rectangle(10, 16, 25, 12)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions Txt_FirstName_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage TxtField_LastName_Screenshot1
        { get { return repo.MakeMyTrip.TravellerDetails.TxtField_LastNameInfo.GetScreenshot1(new Rectangle(13, 19, 20, 9)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions TxtField_LastName_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
